server:
  port: 8080

spring:
  application:
    name: hoangdung-sample-code

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service-fullSkills
    server: http://localhost:${server.port}
    title: Backend service full skills
    version: 1.0.0
